### ISSUE TITLE
Unit of depth image

### ISSUE THREAD

**Issue by mmurooka** [blodow/realtime_urdf_filter#12]
According to http://www.ros.org/reps/rep-0118.html, the unit of depth image should be meter.
OpenNI node, which publishes depth image in millimeters, is irregular.

https://github.com/JimmyDaSilva/realtime_urdf_filter/commit/1b920b9ea79d7d4aa160346213732bb9b219f64d supports only OpenNI node.
We should support both of normal node and OpenNI node.
The encoding of depth image is differ, so we can distinguish normal node and OpenNI node.

**Comment by JimmyDaSilva** [comment]
Sounds like a good plan @mmurooka !
An easy way to do so could to check if the values are below or under 100 before dividing by 1000
``` if z>100 then z/=1000 ```

Or do have something more sophisticated in mind ?

**Comment by mmurooka** [comment]
How about https://github.com/blodow/realtime_urdf_filter/pull/13?
I just confirmed that it works with the kinect in the gazebo environment. (normal node publishing the depth image of meter unit.)
OpenNI node is not tested yet.

**Comment by JimmyDaSilva** [comment]
Seems like a proper way to do it.

**Comment by githubdu** [comment]
![screenshot from 2016-03-23 16 43 22](https://cloud.githubusercontent.com/assets/11909153/13979952/b1ca11d8-f116-11e5-9725-36725fb863fb.png)
Is this right? Why no image received from TOPIC 'output_depth_raw'?

**Comment by githubdu** [comment]
Thank God. Someone noticed this meter unit thing.
