### ISSUE TITLE
realtime_urdf_filter crash

### ISSUE THREAD

**Issue by s880367** [blodow/realtime_urdf_filter#17]
Hi all : 
Recently I run the realtime_urdf_filter by kinectV2 sensor.
The package I used was form @JimmyDaSilva :  [JimmyDaSilva/realtime_urdf_filter](https://github.com/JimmyDaSilva/realtime_urdf_filter)
When I start to launch **filter_kinectV2.launch**, everything went well, but when the node starts to subscribe my kinectV2 topic, the node crashed and the gui will pop up and close immediately.
The follwing the the snapshot for the crashing terminal : 
![](https://i.imgur.com/9dj6JPs.png)

Did anyone meet this problem before ? 
Many thanks at first .

- System : 
Ubuntu 14.04
ROS indigo
GPU : Intel(R) HD Graphics Haswell GT2 Desktop

By the way, everything went well on my other computer
The only difference is the GPU on the other computer is Nvidia GTX970.
Could the GPU cause the crashing problem ?

**Comment by JimmyDaSilva** [comment]
@s880367 All the computation is based on the GPU.
If you managed to make it work on the other computer that probably means that your installation of the gpu is not correct on this one.
What you could do to check quickly is too run libfreenect2 with opengl.
Inside your `libfreenect2/build/bin`, run Protonect with the gl argument: `./Protonect gl`

**Comment by helloshyreckdc** [comment]
@s880367 hello guy, I have the same problem with you. Do you solve this problem finally?   @JimmyDaSilva  I use openni2 to launch a xtion camera, I can't find libfreenect2, do you have any suggestion to debug?

**Comment by JimmyDaSilva** [comment]
@helloshyreckdc libfreenect2 is only for KinectV2 any way.
Well... what happens exactly? any errors ? or just a segfault ?
Can you show what you have on the terminal ?

**Comment by helloshyreckdc** [comment]
@JimmyDaSilva Thank you for reply. I clone this repository and catkin_make successfully. However, when I want to launch realtime_urdf_filter.launch, error occurred.
![error_message](https://user-images.githubusercontent.com/29995816/30692211-17315262-9efd-11e7-860e-1342c2c4b01f.png)
just an exit code -11, the difference between s880367 and me is that his terminal displayed roslaunch will exit while my terminal is just stuck there unless I press ctrl+c to stop it
![error message2](https://user-images.githubusercontent.com/29995816/30692314-950f8ac8-9efd-11e7-851b-1f988848d82b.png)
then I check the log file, but can't find something to solve this problem.
![logfile](https://user-images.githubusercontent.com/29995816/30692477-4bd170be-9efe-11e7-852a-bdcdf4c8620e.png)

**Comment by JimmyDaSilva** [comment]
Ok. Then it's probably related to OpenGL.
I cannot be of any more help than that sorry. You can check PR #19 to see what I discussed there.

Basically make sure you have installed the 3rd party libraries correctly as explained in the README:

> This package requires the following: 3rd party libraries
> 
> GLSL (GL Shader Language) version 1.40 support or greater
> GLEW (GL Extension Wrangler) version 1.6
> NOTE: Trying to use thie package with GLEW 1.5 wil result in a segmentation fault.

**Comment by helloshyreckdc** [comment]
@JimmyDaSilva  Thank you very much! I will check #19, if I have any progress, I will comment here.

**Comment by helloshyreckdc** [comment]
@JimmyDaSilva Hello, you are right! It's the problem of opengl. I have two graphic cards, because of my wrong configuration, the one I used yesterday can support up to opengl 3.0(include GLSL1.30 which not meet the dependency required ), I change the graphic card today, and now the project can work successfully. Thank you again for your kind help!

**Comment by JimmyDaSilva** [comment]
@helloshyreckdc Happy to help. I am glad it works now.

@s880367 Please close this issue
