### ISSUE TITLE
Does this package work with cameras other than Kinects?

### ISSUE THREAD

**Issue by QuantuMope** [blodow/realtime_urdf_filter#31]
Can this package work so long as we specify a depth topic?

**Comment by JimmyDaSilva** [comment]
I have only tried with Kinect and Kinect2 so far.
But it should work with any sensor. The only things it should required are the depth image and camera_info topic.

**Comment by QuantuMope** [comment]
I've been trying to get this package to work with a realsense camera but the package crashes immediately. I didn't specify the camera_info topic though. I don't see it in the list of rosparams or in the sample launch file. How is it specified?

**Comment by JimmyDaSilva** [comment]
Here: https://github.com/blodow/realtime_urdf_filter/blob/5ab2992977855d2e7b430bd279ef3c3ff256a136/src/urdf_filter.cpp#L243

It uses the imageTransport special subscriber to get the image and the camera info as well

**Comment by christian-rauch** [comment]
Yes, this package is sensor agnostic. You just have to provide the camera intrinsic, the transformations and the depth data.

**Comment by QuantuMope** [comment]
Okay, in that case, it seems like this package is crashing for another reason. Will close this issue since it is unrelated. Thanks for the help.

**Comment by blodow** [comment]
@QuantuMope maybe you could open an issue with more info regarding the crash.

**Comment by QuantuMope** [comment]
I currently do not need the package but will do so next time I come across the issues.
