### ISSUE TITLE
support primitive shapes (cylinders, boxes, spheres, ...)

### ISSUE THREAD

**Issue by christian-rauch** [blodow/realtime_urdf_filter#33]
It seems that simple shapes, such as cylinders, are not supported when they are defined by their parameters in the URDF (http://wiki.ros.org/urdf/XML/link#Elements) instead of providing them as mesh.

**Comment by blodow** [comment]
Hey Christian, could you check if your URDF model has the cylinder geometry in the <visual> or the <collision> tags? It's been a couple of years I've been using this package, but my code seems to only look at the <visual> tag. (https://github.com/blodow/realtime_urdf_filter/blob/master/src/urdf_renderer.cpp#L105-L109)

**Comment by christian-rauch** [comment]
It's in the `visual` tag:
```XML
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.0185"/>
      <geometry>
        <cylinder length="0.037" radius="0.035"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
```

I also see it in RViz, but the link is missing in the "Debug" GUI.

**Comment by blodow** [comment]
then maybe it's this here? :D
https://github.com/blodow/realtime_urdf_filter/blob/5ab2992977855d2e7b430bd279ef3c3ff256a136/src/renderable.cpp#L96

**Comment by christian-rauch** [comment]
> then maybe it's this here? :D

Bingo! :-) This fixes the issue.

I added that "fix" to my PR.
