### ISSUE TITLE
Assertion `face.mNumIndices == 3' failed.

### ISSUE THREAD

**Issue by kidpaul94** [blodow/realtime_urdf_filter#36]
Hello,

I appreciate for the great work here! I'm trying to use this package to do the urdf filtering with my mobile robot and ROS **Noetic**. So, I just modified the **realtime_urdf_filter.launch** and  **filter_parameters.yaml**. However, I'm currently facing this error message from here:

https://github.com/blodow/realtime_urdf_filter/blob/4051fe6a8ba5b269e229aa7da3796067e638ab5e/src/renderable.cpp#L408

Would you mind giving me some ideas about any reason possibly causing this assertion fail?

Thank you.

**Comment by Yitian-Xian** [comment]
Hi @kidpaul94, I am encountered with similar problems when I am working on the Franka Emika Panda robot and using their provided models. Do you fix this issue? If so, could you please tell me how to do that? Thanks!!

Hi @blodow, could you please provide any guidance on the second suggestion? Do I need to modify the stl or the dae file? Thank you!!

**Comment by Yitian-Xian** [comment]
Hi @blodow, @kidpaul94, I have found a link https://github.com/AndrejOrsula/panda_ign_moveit2/tree/master/panda_description. If you check this link, we can see that the stl file does have some polygons, which may cause the problem. Could you please tell me how to fix? Thx!

**Comment by blodow** [comment]
So i see two ways:

if you could improve the code where the assert fails so it is able to deal
with more than three vertices per mesh face, that would be perfect. Or
would also be helpful to future users of the urdf filter.

Short of that, you would have to load the mesh  in some external program
and convert all quads/n-gons to triangles. Meshlab and blender are both
great tools to know.

Here is a inspirational link that mentions solutions for both cases:

https://gamedev.stackexchange.com/a/45685

I hope this helps. And again, a PR with a fix would be much appreciated 😅

**Comment by Yitian-Xian** [comment]
Hi @blodow, thank you for your answer. Since I am not familiar with computer graphics, I would prefer the second way. Could you please tell me whether I should fix the stl or dae file?

**Comment by blodow** [comment]
that depends which model is actually loaded, which depends on what your
launch files and config files define. i’m afraid you will have to just
trace that..
